CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(25) NOT NULL DEFAULT '0',
	`firstName` VARCHAR(50) NOT NULL DEFAULT '0',
	`lastName` VARCHAR(50) NOT NULL DEFAULT '0',
	`email` VARCHAR(200) NOT NULL DEFAULT '0',
	`password` VARCHAR(32) NOT NULL DEFAULT '0',
	`signUpDate` DATETIME NULL DEFAULT NULL,
	`profilePic` VARCHAR(500) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
